name: tests.py
on:
  push:
    paths:
    - '**.py'
    - '!bots/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pipenv
        pipenv install
    - name: Run tests.py
      run: |
        pipenv run python tests.py
